#!/bin/bash
#$1 risultato operazione 
#$2 file
error(){
    if [ $1 -ne 0 ]
    then
        echo "ERROR ON FILE: $2"
        exit -1
    fi
}

#$1 file 
vhdl(){
    vcom -93 $1
    error $? $1
}

vhdl bresenham_axis.vhd  
vhdl cnc_3axis_controller.vhd  
vhdl cnc_pkg.vhd  
vhdl encoder_decoder.vhd    
vhdl rom_controller.vhd      
vhdl trajectory_rom.vhd
vhdl cnc_3axis_controller_synth.vhd  
vhdl cnc_3axis_rom_top.vhd  
vhdl encoder_simulator.vhd  
vhdl step_dir_generator.vhd  
